name: guess_the_number
description: simple game

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.3
  presentation:
    path: packages/presentation
  domain:
    path: packages/domain

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: 2.2.0
  injectable_generator: 1.5.4

flutter:

  uses-material-design: true