name: presentation
description: Presentation
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.3
  domain:
    path: ../domain

dev_dependencies:
  lints: ^2.0.0
  build_runner: 2.2.0
  injectable_generator: 1.5.4