name: on_master_commit

on:
  push:
    branches:
      - master
jobs:
  commit_master:
    name: commit to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - run: echo $ANDROID_HOME
      - run: sdkmanager --install "ndk;23.1.7779620"
      - run: sdkmanager --install "build-tools;30.0.3"
      - name: Domain Pub Get
        run: |
          cd packages/domain/
          flutter pub get
      - name: presentation Pub Get
        run: |
          cd packages/presentation/
          flutter pub get
      - name: App Pub Get
        run: flutter pub get

      - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: flutter test integration_test
          api: 31
          cmdOptions: -no-snapshot-save -noaudio -no-boot-anim -cores 2 -memory 3072 -no-window
          tag: google_apis
          abi: x86_64

#      - name: Build release
#        run: flutter build apk --release
#      - name: Publish
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: build/app/outputs/flutter-apk/app-release.apk
#          tag: releases
#          token: ${{ secrets.TOKEN_G_H }}
