name: on_master_commit

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master
jobs:
  commit_master:
    name: commit to master
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level:
          - 29
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Domain Pub Get
        run: |
          cd packages/domain/
          flutter pub get
      - name: presentation Pub Get
        run: |
          cd packages/presentation/
          flutter pub get
      - name: App Pub Get
        run: flutter pub get
      - name: Test
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test --verbose

#      - name: Build release
#        run: flutter build apk --release
#      - name: Publish
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: build/app/outputs/flutter-apk/app-release.apk
#          tag: releases
#          token: ${{ secrets.TOKEN_G_H }}
