name: on_master_commit

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master
jobs:
  commit_master:
    name: commit to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Domain Pub Get
        run: |
          cd packages/domain/
          flutter pub get
      - name: presentation Pub Get
        run: |
          cd packages/presentation/
          flutter pub get
      - name: App Pub Get
        run: flutter pub get
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
        with:
          cmd: flutter doctor -v
          api: 25
          tag: default
          abi: x86
      - run: sdkmanager platform-tools
      - run: adb devices
      - run: echo $ANDROID_HOME
      - run: flutter drive --driver integration_test/driver.dart --target integration_test/int_test.dart
#      - name: Build release
#        run: flutter build apk --release
#      - name: Publish
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: build/app/outputs/flutter-apk/app-release.apk
#          tag: releases
#          token: ${{ secrets.TOKEN_G_H }}

#
